---

extends: default

# ignore: |

rules:
  line-length: disable
  colons:
    max-spaces-before: 0
    max-spaces-after: -1   # -1 = unlimited, disables the after-colon check
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: -1   # -1 = unlimited, disables the after-comma check
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  truthy:
    check-keys: false
